DATASET:
  TRAIN:
    TYPE: 'Scoliosis_X_ray'
    ROOT: '/home/jackson/Documents/Project_BME/Datasets/scoliosis/xray/boostnet_labeldata/'
    IMG_PREFIX: 'data/training'
    ANN: 'labels/training'
    AUG:
      FLIP: false
      ROT_FACTOR: 20
      SCALE_FACTOR: 0.25
      NUM_JOINTS_HALF_BODY: 0
      PROB_HALF_BODY: 0
  VAL:
    TYPE: 'Scoliosis_X_ray'
    ROOT: '/home/jackson/Documents/Project_BME/Datasets/scoliosis/xray/boostnet_labeldata/'

    IMG_PREFIX: 'data/test'
    ANN: 'labels/test'
  TEST:
    TYPE: 'Scoliosis_X_ray'
    ROOT: '/home/jackson/Documents/Project_BME/Datasets/scoliosis/xray/boostnet_labeldata/'
    IMG_PREFIX: 'data/test'
    DET_FILE: './exp/json/test_det_rcnn.json'
    ANN: 'labels/test'
DATA_PRESET:
  TYPE: 'scoliosis'
  SIGMA: 2
  NUM_JOINTS: 68
  IMAGE_SIZE:
  - 1024
  - 512
  HEATMAP_SIZE:
  - 256
  - 128
MODEL:
  TYPE: 'RegressFlow'
  PRETRAINED: '/home/jackson/Documents/Project_BME/Python_code/NF/res-loglikelihood-regression/exp/test_rle-1024x512_res50_scoliosic_regress-flow.yaml/model_3357.pth'
  TRY_LOAD: ''
  NUM_FC_FILTERS:
  - -1
  HIDDEN_LIST: -1
  NUM_LAYERS: 50
LOSS:
  TYPE: 'RLELoss'
TEST:
  HEATMAP2COORD: 'coord'
TRAIN:
  WORLD_SIZE: 8
  BATCH_SIZE: 8
  BEGIN_EPOCH: 0
  END_EPOCH: 2000
  OPTIMIZER: 'adam'
  LR: 0.0005
  LR_FACTOR: 0.1
  LR_STEP:
  - 500
  - 1000